### ISSUE TITLE
Task 4: Create Espresso Tests

### ISSUE THREAD

**Issue by JeremyWildsmith** [COMP7082Group2/PhotoGallery#2]
Task 4:  Create automated acceptance test for the Time based and Keyword based search using Espresso.  It is understood that these tests will fail for now as there is no functionality behind this GUI. 

The test shall automatically invoke Gallery Activity, press the search  button of this Activity to bring Search Activity to the foreground, enter startdate, enddate and/or keywords that should result in finding only one photo, press OK button to bring back the Gallery Activity, check the timestamp and caption to verify that the right picture was found.

**Comment by JeremyWildsmith** [comment]
Basic espresso tests are done, but can't finish them until rest of functionality is done. So I will leave this issue open for now.

**Comment by jeiyang108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [S01-T04. Create Espresso Tests](https://trello.com/c/CXEgpwfl/4-s01-t04-create-espresso-tests)
