### ISSUE TITLE
Task 8 & 9

### ISSUE THREAD

**Issue by JeremyWildsmith** [COMP7082Group2/PhotoGallery#6]
Assuming that a list of filepaths already exists and accessible, implement the navigation functionality that involves managing an index and displaying a different photo via ImageView in response to left and right button click.

**Comment by JeremyWildsmith** [comment]
Task 9: Implement the functionality that allows user to assign or change a caption of the Photo currently being displayed.

**Comment by JeremyWildsmith** [comment]
Record testing / CI & demo:

    [4 marks] Demo of the automated testing of the time and keyword based search functionality [end of Sprint I]
    [2 marks] Demo of the automated build and testing using Git/Jenkins or some other alternative CIT solution showing that build was successful and automated tests ran

**Comment by jeiyang108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [S01-T08. Implement the Navigation functionality](https://trello.com/c/TDrvIACf/8-s01-t08-implement-the-navigation-functionality)

**Comment by jeiyang108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [S01-T09. Implement the Caption functionality](https://trello.com/c/62OdeSqT/9-s01-t09-implement-the-caption-functionality)
